name: Docker Image CI

on:
  push:
    branches: [ "main", "feature/*"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pg_dumper:$(date +%s)
    - name: List the available Docker images
      run: docker images
    - name: run the Docker image
      run: docker run pg_dumper:$(date +%s) --help
